# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  NodeCount = 3

  # Kubernetes Nodes
  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "generic/ubuntu2004"
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network "private_network", ip: "192.168.122.11#{i}"
      node.vm.provider :libvirt do |v|
        v.memory = 2048
        v.cpus = 2
      end
    end
  end

end
